"use client";
import { FormEvent, useState } from "react";
import { useRouter } from "next/navigation";
import { PageHeader } from "@/components/ui";
import { createTrip } from "@/lib/api";

const initial={flight_number:"MU5105",departure_airport:"SHA",arrival_airport:"PEK",departure_at:"2026-08-10T14:30",arrival_at:"2026-08-10T16:50",departure_terminal:"T2",arrival_terminal:"T2",party_adults:1,party_children:0};
export default function ImportTripPage(){const router=useRouter();const [mode,setMode]=useState("manual");const [form,setForm]=useState(initial);const [busy,setBusy]=useState(false);const [error,setError]=useState("");
async function submit(event:FormEvent){event.preventDefault();setBusy(true);setError("");try{const trip=await createTrip({...form,departure_at:new Date(form.departure_at).toISOString(),arrival_at:new Date(form.arrival_at).toISOString()});router.push(`/trips/${trip.id}`)}catch(value){setError(value instanceof Error?value.message:"创建失败")}finally{setBusy(false)}}
return <><PageHeader eyebrow="行程导入" title="添加新的旅行行程" description="支持截图、行程单、文本、航班号和手工录入；当前Demo使用模拟解析。"/><div className="tabs">{[["upload","上传文件"],["text","粘贴文本"],["flight","航班号"],["manual","手工填写"]].map(([id,label])=><button className={mode===id?"active":""} key={id} onClick={()=>setMode(id)}>{label}</button>)}</div>{mode!=="manual"?<section className="card upload-panel"><div className="upload-symbol">↑</div><h2>{mode==="upload"?"上传机票截图或PDF":mode==="text"?"粘贴行程文本":"输入航班号与日期"}</h2><p>该入口已完成交互设计，Demo会载入示例MU5105并进入字段确认。</p><button className="button primary" onClick={()=>setMode("manual")}>使用示例解析结果</button></section>:<form className="card form-panel" onSubmit={submit}><div className="form-grid"><label>航班号<input value={form.flight_number} onChange={e=>setForm({...form,flight_number:e.target.value})}/></label><label>出发日期时间<input type="datetime-local" value={form.departure_at} onChange={e=>setForm({...form,departure_at:e.target.value})}/></label><label>出发机场<input maxLength={3} value={form.departure_airport} onChange={e=>setForm({...form,departure_airport:e.target.value})}/></label><label>到达机场<input maxLength={3} value={form.arrival_airport} onChange={e=>setForm({...form,arrival_airport:e.target.value})}/></label><label>出发航站楼<input value={form.departure_terminal} onChange={e=>setForm({...form,departure_terminal:e.target.value})}/></label><label>到达航站楼<input value={form.arrival_terminal} onChange={e=>setForm({...form,arrival_terminal:e.target.value})}/></label><label>成人人数<input type="number" min={1} value={form.party_adults} onChange={e=>setForm({...form,party_adults:Number(e.target.value)})}/></label><label>儿童人数<input type="number" min={0} value={form.party_children} onChange={e=>setForm({...form,party_children:Number(e.target.value)})}/></label><label className="wide">到达日期时间<input type="datetime-local" value={form.arrival_at} onChange={e=>setForm({...form,arrival_at:e.target.value})}/></label></div>{error&&<div className="alert danger">{error}</div>}<div className="action-row end"><button className="button primary" disabled={busy}>{busy?"正在保存…":"保存并确认字段"}</button></div></form>}</>}
